// JavaScript (JS) is a lightweight, interpreted, or just-in-time compiled programming language with first-class functions.

"use strict";
// ----------------------------------------------------------//

// Brendon Eich is the founder of JS

// ------------------------------------------------------------- //

// console.log can print something on console

console.log("Hello World!");
// console.log('Hello World2');
// console.log(`Hello World3`);

// ------------------------------------------------------------------//

// Taking input from user
// Note:- prompt() will give the string output only

let guess = prompt("Guess the number", "Enter your number here");
var num = prompt(typeof num);
var variable = alert("Hello there");

console.log("\n"); // New line

// Window confirm() method -> Takes string as an argument

const agree = confirm("Are you sure you want to delete this item");
console.log(agree);

// -------------------------------------------------------------------------//

// Variables

/*Varibles can store information
We can use that info later
We can change that information later 

We cannot start with number Eg:- 1value(invalid) & value1(valid) 
We can use only (underscore)_ and (doller)$ symbol
We cannot use spaces first name(invalid)
Convention is to start with small letter and use camelCase

*/

var first_name = "KrunalGupta"; // snake case writing
var firstName = "KrunalGupta"; // camel case writing

var firstName = "Krunal"; // Declaration
console.log(firstName);

var firstName = "Harshit"; // This will not throw any error
console.log(firstName);

// let Keyword
// We can use let keyword to declare variable just like var keyword
// The main difference is one is block scope and another is function scope

let value = 10;
// let value = 11;          // This will throw error
console.log(value ** 2); // Taking power

// Constants

const pi = 3.14;
console.log(pi * 2 * 2);

// ------------------------------------------------------------------------------------------//

// typeof Operator -> It is used to identify which data type it is

// Data Types (Primitive Data type)
//--> Immuttable

// Number 1, 2, 3
// String "Krunal"
// booleans
// undefined
// null
// BigInt
// Symbol - A unique value that can be generated by Symbol constructor

// Data Types (Non-Primitive Data type)
//--> Mutable

// Array
// Objects

let age = 22;
let firstNaame = "krunal";

console.log(typeof age);
console.log(typeof firstNaame);

// Convert number to string

age = age + "";
console.log(typeof age);

// Convert string to number

// let str = +"34";
// console.log(typeof str);

// let age1 = "18";
// age = Number(18);
// console.log(typeof age);

// let myVar;
// console.log(myVar); // This is undefined
// myVar = "Hi";
// console.log(myVar, typeof myVar);

// let myVariable = null;
// console.log(myVariable);
// console.log(typeof null); //This is bug or error in Js

// BigInt

// Declaration
let big1 = 123n;
let big2 = BigInt(123);

console.log(big1, typeof big1);
console.log(big2, typeof big2);

console.log(big1 + big2);

// To check the range of data type
console.log(Number.MAX_SAFE_INTEGER);

// Boolean and Comparison Operator

let num1 = 8;
let num2 = 8;

console.log(num1 > num2);
console.log(num1 >= num2);

let num3 = "7";
let num4 = 7;

console.log(num3 == num4); // == operator only check value not data type
console.log(num3 === num4); // === operator checks both value and data type

console.log(num3 != num4); // != operator only checks value not data type
console.log(num3 !== num4); // !== operator checks both value and data type

// Casting in JS

// 1) String to Int
// - parseInt()
// - Number()
// - Plus sign(+)

let newNum = "10";
// let numInt = parseInt(newNum);
// let numInt = Number(newNum);
let numInt = +newNum;
console.log(numInt);

// 2) String to float
// - parseFloat()
// - Number()
// - plus sign(+)

let float = 3.71;
let numFloat = parseFloat(float);
// let numFloat = Number(float);
// let numFloat = +float;
console.log(numFloat);

// 3) Float to int
// - parseInt()

let number = 9.81;
let newNumInt = parseInt(number);
console.log(newNumInt);

// Time Functions

// In JS we use JS Date object to get current time and date

// Date Functions:-
// 1. getFullYear()
// 2. getMonth()
// 3. getDate()
// 4. getHours()
// 5. getMinutes()
// 6. getSeconds()
// 7. getMilliseconds()
// 8. getTime()
// 9. getDay()

// Creating time object
const now = new Date();

console.log(now);

console.log(now.getFullYear());

console.log(now.getMonth()); // Month(0-11)

console.log(now.getDate());

console.log(now.getDay()); // 1 bcz day is Monday day(0-6)

console.log(now.getHours());

console.log(now.getMinutes());

console.log(now.getSeconds());

// Getting Time
// -> This method give time in milliseconds starting from Jan 1, 1970. It is also know as unix time

console.log(now.getTime());

console.log(Date.now());

console.log(
  now.getDate(),
  now.getMonth(),
  now.getFullYear(),
  now.getHours(),
  now.getMinutes()
);
