package recursion;

import java.util.Scanner;

public class Questions {

	public static void main(String[] args) {
		
		String a = "abcba" ;
	
		System.out.println(palindrome(a, 0, a.length()-1));
		
		reverseString(a);
	
	
	}
	
	static boolean palindrome(String s , int l , int r) {
		
		if(l == r ) {
			return true ;
		}
		if(s.charAt(l) != s.charAt(r)) {
			return false ;
		}
		if(l < r+1 ) {
			return palindrome(s, l+1, r-1);
		}
		return true ;
	}
	
	static void reverseString(String s) {
		if(s.length() == 1) {
			System.out.println(s);
		} else {
			System.out.print(s.charAt(s.length()-1));
			reverseString(s.substring(0,s.length()-1));
		}
		
	}
	
	static void subsequenceString(String s) {
//		A String is a subsequence of a given String, that is generated by deleting some character of a 
//		given string without changing its order.
		
		subsequenceString("abc", "");
	}
	
	static void subsequenceString(String ques, String ans) {
		if(ques.length() == 0) {
		    System.out.print(ans + ", ");
		    return;
		}

		subsequenceString(ques.substring(1), ans+ques.charAt(0));
		subsequenceString(ques.substring(1), ans);
    	}
	
	public static void main (String[] args) {
		int a[] = {1, 2, 3, 5} ;
		shuffle(a , 3 , 3);
	}
	
	static void shuffle(int arr [] , int n , int a ) {

	    if(a-n >= 0 ) {
	    	System.out.print(arr[a - n] + " " + arr[n/2 + 1] + " ");
	    	shuffle(arr , n-1 , n);
	    }
	    
	}
}
